SELECT COUNT(ORDER_ID) TOTAL_ORDERS FROM ORDERS;
SELECT SUM(PIZZAS.PRICE*ORDER_DETAILS.QUANTITY) TOTAL_REVENUE FROM ORDER_DETAILS INNER JOIN PIZZAS ON ORDER_DETAILS.PIZZA_ID=PIZZAS.PIZZA_ID;
SELECT PT.NAME,P.PRICE FROM PIZZA_TYPES PT INNER JOIN PIZZAS P ON PT.PIZZA_TYPE_ID=P.PIZZA_TYPE_ID WHERE P.PRICE=(SELECT MAX(PRICE) FROM PIZZAS);
SELECT PIZZA_SIZE,COUNT(QUANTITY) PIZZAS_ORDERED FROM (SELECT * FROM PIZZAS INNER JOIN ORDER_DETAILS ON PIZZAS.PIZZA_ID=ORDER_DETAILS.PIZZA_ID) PIZZA_ORSER_DETAILS GROUP BY PIZZA_SIZE ORDER BY PIZZAS_ORDERED DESC FETCH FIRST 1 ROWS ONLY;
SELECT PIZZA_TYPES.NAME,COUNT(ORDER_DETAILS.QUANTITY) TOTAL_ORDERS FROM PIZZA_TYPES  INNER JOIN PIZZAS  ON PIZZAS.PIZZA_TYPE_ID=PIZZA_TYPES.PIZZA_TYPE_ID JOIN ORDER_DETAILS ON PIZZAS.PIZZA_ID=ORDER_DETAILS.PIZZA_ID GROUP BY PIZZA_TYPES.NAME ORDER BY TOTAL_ORDERS DESC FETCH FIRST 1 ROWS ONLY;
